// Taken from the Wikipedia page http://en.wikipedia.org/wiki/List_of_former_members_of_the_United_States_House_of_Representatives_(A)
var members = [
    ['1', 'admin','管理员'],
    ['2', 'a','老师'],
	['2', 'b','老师'],
	['2', 'c','老师'],
	['2', 'd','老师'],
    ['3', 'zhangsan', '学生'],
	['3', 'lisi', '学生'],
	['3', 'wangwu', '学生'],
	['3', '赵六', '学生'],
	['3', '钱七', '学生'],
	['3', '小周', '学生'],
	['3', 'lisi', '学生'],
	['3', 'wangwu', '学生'],
	['3', '赵六', '学生'],
	['3', '钱七', '学生'],
	['3', '小周', '学生'],
	['3', 'lisi', '学生'],
	['3', 'wangwu', '学生'],
	['3', '赵六', '学生'],
	['3', '钱七', '学生'],
	['3', '小周', '学生'],
];
